dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "Storyguide",
    "Storypath",
    "afterbegin",
    "attunements",
    "beforeend",
    "contextmenu",
    "curseborne",
    "depthless",
    "enh",
    "enricher",
    "enrichers",
    "ethaks",
    "flexcol",
    "flexrow",
    "flexshrink",
    "inplace",
    "lifecycle",
    "minimizable",
    "oklab",
    "reroll",
    "rerolls",
    "rgx",
    "spu",
    "telelocation",
    "unlist",
    "unshift",
]
